#!/usr/bin/env php
<?php

use Hooks\Command;
use Symfony\Component\Console\Application;



foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('BETACIE_HOOKS_COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('BETACIE_HOOKS_COMPOSER_INSTALL')) {
    echo 'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL;
    die(1);
}

require BETACIE_HOOKS_COMPOSER_INSTALL;


$console = new Application();

$console->add(new Command\InstallCommand());
$console->add(new Command\TriggerCommand());

$console->run();